name: pull-request
on:
  pull_request:
    branches:
      - main
permissions:
  contents: write
  id-token: write
env:
  WORKLOAD_IDENTITY_PROVIDER: 'projects/511247202360/locations/global/workloadIdentityPools/github-actions/providers/github-actions-versori'
  WORKLOAD_IDENTITY_SERVICE_ACCOUNT: 'gh-actions-versori@versori.iam.gserviceaccount.com'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Modules
        run: npm ci
      - name: Build
        run: npm run build
