name: release
on:
  push:
    branches:
      - main
permissions:
  contents: write
  id-token: write
env:
  WORKLOAD_IDENTITY_PROVIDER: 'projects/511247202360/locations/global/workloadIdentityPools/github-actions/providers/github-actions-versori'
  WORKLOAD_IDENTITY_SERVICE_ACCOUNT: 'gh-actions-versori@versori.iam.gserviceaccount.com'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup Google Cloud Authentication
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.WORKLOAD_IDENTITY_SERVICE_ACCOUNT }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Install dependencies
        run: npm ci
      - name: Lint & Formatting
        run: npm run check
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: GCP Artifact Registry Login
        run: |
          npx google-artifactregistry-auth
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: ^18.0.0
          extra_plugins: |
            @semantic-release/changelog@^6.0.1
            @semantic-release/git@^10.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.VERSORI_REPOS_PAT }}
          HUSKY: 0
